### ISSUE TITLE
Team Detail pages are not centered

### ISSUE THREAD

**Issue by DivinoAG** [crystalhelix/companysite#66]
On the Team Detail, the head diamond and the text content is not being centered horizontally, instead is slightly off to the right on all screen sizes.

**Comment by natecox** [comment]
I think this is caused by my fix for getting rid of the blue margin at the right of the screen.

The page was set up using `100vw` width and a margin of `-5vw`, which was pulling the content 5vw to the left. I changed the content to `110vw` to compensate, but it seems to have moved everything slightly to the right.

**Comment by natecox** [comment]
This should be resolved now.
